version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=vulnerable_app
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=vulnerable_app
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: